### ISSUE TITLE
Websocket client

### ISSUE THREAD

**Issue by inakifeliu** [nioc/jeedom-websocket#2]
First of all thank you for your efforts in this plugin.

I'm looking for a jeedom websocket client to connect to my Daikin heating machine, from what I read, your plugin is a server, isn't it?

Do you have any idea how to do this?

Thank you!

**Comment by nioc** [comment]
Hello, this plugin allows to read and broadcast events (jeedom info updates mainly) through websocket. I wrote a little example for a JavaScript client.
What is your need?

**Comment by inakifeliu** [comment]
Hello,
My needs are reading events from a Daikin heating system and pass the
values to Jeedom.
Thank you.

Missatge de Nicolas <notifications@github.com> del dia dv., 8 de gen. 2021
a les 3:06:

**Comment by nioc** [comment]
Ok, i do not know Daikin systems, maybe it exposes a REST API you can call for getting values, another way should be making a small physical data reader (with an arduino for example) and send MQTT messages (there is a good jeedom plugin).
In both case, websocket plugin can not achieve your goal.

**Comment by nioc** [comment]
There is an existing plugin for Daikin, may be it shoulds suit your needs:
https://jeedom.github.io/documentation/third_plugin/DaikinOnlineCtrl/fr_FR/index.html
